let hsk10 = [
"汽车\t汽車\tqi4che1\tqìchē\tcar",
"门口\t門口\tmen2kou3\tménkǒu\tentrance; doorway",
"工人\t工人\tgong1ren2\tgōngrén\tworker",
"工装\t工裝\tgong1zhuang1\tgōngzhuāng\tuniform",
"公司\t公司\tgong1si1\tgōngsī\tcompany",
"厉害\t厲害\tli4hai5\tlìhai\tskilled; amazing",
"好奇\t好奇\thao4qi2\thàoqí\tcurious",
"神奇\t神奇\tshen2qi2\tshénqí\tamazing",
"参观\t參觀\tcan1guan1\tcānguān\tto visit",
"那些\t那些\tna4xie1\tnàxiē\tthose",
"就是\t就是\tjiu4shi4\tjiùshì\tjust is / are",
"这里\t這裡\tzhe4li3\tzhèlǐ\there",
"用\t用\tyong4\tyòng\tto use",
"一样\t一樣\tyi1yang4\tyīyang\tsame",
"统一\t統一\ttong3yi1\ttǒngyī\tunified",
"表示\t表示\tbiao3shi4\tbiǎoshì\tto represent; to indicate",
"继续\t繼續\tji4xu4\tjìxù\tto continue",
"样子\t樣子\tyang4zi5\tyàngzi\tappearance; way",
"中信戴卡\t中信戴卡\tzhong1xindai4ka3\tzhōngxìndàikǎ\tDicastal",
"工厂\t工廠\tgong1chang3\tgōngchǎng\tfactory",
"机器\t機器\tji1qi4\tjīqì\tmachine",
"原材料\t原材料\tyuan2cai2liao4\tyuáncáiliào\traw material",
"生产\t生產\tsheng1chan3\tshēngchǎn\tto produce",
"生产线\t生產線\tsheng1chan3xian4\tshēngchǎnxiàn\tproduction line",
"铝车轮\t鋁車輪\tlv3che1lun2\tlǚchēlún\taluminum wheel",
"制造\t製造\tzhi4zao4\tzhìzào\tto manufacture",
"铸件\t鑄件\tzhu4jian4\tzhùjiàn\tcasting",
"车间\t車間\tche1jian1\tchējiān\tworkshop",
"机器人\t機器人\tji1qi4ren2\tjīqìrén\trobot",
"自动化\t自動化\tzi4dong4hua4\tzìdònghuà\tautomation",
"数智化\t數智化\tshu4zhi4hua4\tshùzhìhuà\tdigitalization and intelligence",
"传感器\t傳感器\tchuan2gan3qi4\tchuángǎnqì\tsensor",
"数据分析\t數據分析\tshu4jufen1xi1\tshùjùfēnxī\tdata analysis",
"质量控制\t質量控制\tzhi4liang4kong4zhi4\tzhìliàngkòngzhì\tquality control",
];