let hsk4 = [
"员工\t員工\tyuan2gong1\tyuángōng\temployee",
"工作\t工作\tgong1zuo4\tgōngzuò\twork; job",
"加入\t加入\tjia1ru4\tjiārù\tto join",
"团队\t團隊\ttuan2dui4\ttuánduì\tteam",
"了解\t了解\tliao3jie3\tliǎojiě\tto understand / understanding",
"文化\t文化\twen2hua4\twénhuà\tculture",
"历史\t歷史\tli4shi3\tlìshǐ\thistory",
"兴趣\t興趣\txing4qu4\txìngqù\tinterest",
"接触\t接觸\tjie1chu4\tjiēchù\tto contact; to touch",
"特色\t特色\tte4se4\ttèsè\tcharacteristic; specialty",
"节日\t節日\tjie2ri4\tjiérì\tfestival; holiday",
"传统\t傳統\tchuan2tong3\tchuántǒng\ttradition",
"听说\t聽說\tting1shuo1\ttīngshuō\tto hear (about); it is said",
"放假\t放假\tfang4jia4\tfàngjià\tto have a holiday",
"家人\t家人\tjia1ren2\tjiārén\tfamily member",
"氛围\t氛圍\tfen1wei2\tfēnwéi\tatmosphere",
"交流\t交流\tjiao1liu2\tjiāoliú\tto communicate; to exchange",
"友谊\t友誼\tyou3yi4\tyǒuyì\tfriendship",
"习俗\t習俗\txing2shi4\txíngshì\tcustom",
"习惯\t習慣\txi2guan4\txíguàn\thabit / to get used to",
"主意\t主意\tzhu3yi4\tzhǔyì\tidea; opinion",
"意义\t意義\tyi4yi4\tyìyì\tmeaning; significance",
"准备\t準備\tzhun3bei4\tzhǔnbèi\tto prepare / preparation",
"中国\t中國\tzhong1guo2\tzhōngguó\tChina",
"摩洛哥\t摩洛哥\tmo2luo4ge1\tmóluògē\tMorocco",
"突尼斯\t突尼斯\ttu1ni2si1\ttūnísi1\tTunisia",
"中信戴卡\t中信戴卡\tzhong1xindai4ka3gong1si1\tzhōngxìndàikǎgōngsī\tCITIC Dicastal",
"美国\t美國\tmei3guo2\tměiguó\tUnited States",
"法国\t法國\tfa3guo2\tfǎguó\tFrance",
"英国\t英國\tying1guo2\tyīngguó\tUnited Kingdom",
"意大利\t意大利\tyi4da4li4\tyìdàlì\tItaly",
"欧洲\t歐洲\tou1zhou1\tōuzhōu\tEurope",
"非洲\t非洲\tfei1zhou1\tfēizhōu\tAfrica",
"春节\t春節\tchun1jie2\tchūnjié\tSpring Festival",
];