let hsk6 = [
"办公室\t辦公室\tban4gong1shi4\tbàngōngshì\toffice",
"前面\t前面\tqian2mian4\tqiánmiàn\tfront; ahead",
"后面\t後面\thou4mian4\thòumiàn\tback; behind",
"左边\t左邊\tzuo3bian1\tzuǒbiān\tleft side",
"右边\t右邊\tyou4bian1\tyòubiān\tright side",
"旁边\t旁邊\tpang2bian1\tpángbiān\tbeside; next to",
"对面\t對面\tdui4mian4\tduìmiàn\topposite; across",
"楼上\t樓上\tlou2shang4\tlóushàng\tupstairs",
"楼下\t樓下\tlou2xia4\tlóuxià\tdownstairs",
"中间\t中間\tzhong1jian1\tzhōngjiān\tmiddle; center",
"走廊\t走廊\tzou3lang2\tzǒuláng\tcorridor; hallway",
"拐角\t拐角\tguai3jiao3\tguǎijiǎo\tcorner; turn",
"入口\t入口\tru4kou3\trùkǒu\tentrance",
"出口\t出口\tchu1kou3\tchūkǒu\texit",
"电梯\t電梯\tdian4ti1\tdiàntī\televator",
"办公区\t辦公區\tban4gong1qu1\tbàngōngqū\toffice area",
"会议室\t會議室\thui4yi4shi4\thuìyìshì\tmeeting room",
"茶水间\t茶水間\tcha2shui3jian1\tcháshuǐjiān\ttea room",
"前台\t前台\tqian2tai2\tqiántái\treception desk",
"行政部门\t行政部門\txing2zheng4bu4men2\txíngzhèngbùmén\tadministrative department",
"研发中心\t研發中心\tyan2fazhong1xin1\tyánfāzhōngxīn\tR&D center",
"生产车间\t生產車間\tsheng1chan3che1jian1\tshēngchǎnchējiān\tproduction workshop",
"员工休息区\t員工休息區\tyuan2gong1xiu1xi5qu1\tyuángōngxiūxiqu1\tstaff rest area",
"接待处\t接待處\tjie1daichu4\tjiēdàichù\treception area",
"门禁系统\t門禁系統\tmen2jin4xi4tong3\tménjìnxìtǒng\taccess control system",
];