let hsk8 = [
"多少\t多少\tduo1shao3\tduōshǎo\thow many; how much",
"人数\t人數\tren2shu4\trénshù\tnumber of people",
"公司\t公司\tgong1si1\tgōngsī\tcompany",
"员工\t員工\tyuan2gong1\tyuángōng\temployee",
"部门\t部門\tbu4men2\tbùmén\tdepartment",
"团队\t團隊\ttuan2dui4\ttuánduì\tteam",
"一共\t一共\tyi1gong4\tyīgòng\taltogether; in total",
"大约\t大約\tda4yue1\tdàyuē\tapproximately",
"了解\t了解\tliao3jie3\tliǎojiě\tto understand",
"询问\t詢問\txun2wen4\txúnwèn\tto inquire",
"回答\t回答\thui2da2\thuídá\tto answer",
"情况\t情況\tqing2kuang4\tqíngkuàng\tsituation",
"需要\t需要\txu1yao4\txūyào\tto need / need",
"帮助\t幫助\tbang1zhu4\tbāngzhù\tto help",
"谢谢\t謝謝\txie4xie5\txièxie\tthank you",
"统计\t統計\ttong3ji4\ttǒngjì\tto count; to tally / statistics",
"人力资源部\t人力資源部\tren2lizi1yuan2bu4\trénlìzīyuánbù\thuman resources department",
"财务部\t財務部\tcai2wu4bu4\tcáiwùbù\tfinance department",
"技术部\t技術部\tji4shubu4\tjìshùbù\ttechnical department",
"市场部\t市場部\tshi4chang3bu4\tshìchǎngbù\tmarketing department",
"销售部\t銷售部\txiao1shou4bu4\txiāoshòubù\tsales department",
"客户服务部\t客戶服務部\tke4hufu2wu4bu4\tkèhùfúwùbù\tcustomer service department",
"研发中心\t研發中心\tyan2fazhong1xin1\tyánfāzhōngxīn\tR&D center",
"生产车间\t生產車間\tsheng1chan3che1jian1\tshēngchǎnchējiān\tproduction workshop",
"行政部\t行政部\txing2zheng4bu4\txíngzhèngbù\tadministrative department",
"物流部\t物流部\twu4liubu4\twùliúbù\tlogistics department",
"采购部\t採購部\tcai3gou4bu4\tcǎigòubù\tprocurement department",
"项目组\t項目組\txiang4mu4zu3\txiàngmùzǔ\tproject team",
];