let hsk9 = [
"现在\t現在\txian4zai4\txiànzài\tnow / now",
"几点\t幾點\tji3dian3\tjǐdiǎn\twhat time",
"午餐\t午餐\twu3can1\twǔcān\tlunch",
"提醒\t提醒\tti2xing3\tíxǐng\tto remind",
"迅速\t迅速\txun4su4\txùnsù\trapid; quick",
"争取\t爭取\tzheng1qu3\tzhēngqǔ\tto strive for",
"顺利\t順利\tshun4li4\tshùnlì\tsmooth; successful",
"克服\t克服\tke4fu2\tkèfú\tto overcome",
"困难\t困難\tkun4nan2\tkùnnán\tdifficulty / difficult",
"保证\t保證\tbao3zheng4\tbǎozhèng\tto guarantee / guarantee",
"准时\t準時\tzhun3shi2\tzhǔnshí\ton time",
"设计\t設計\tshe4ji4\tshèjì\tdesign / to design",
"明白\t明白\tming2bai2\tmíngbái\tto understand / clear",
"问题\t問題\twen4ti2\twèntí\tquestion; problem",
"看看\t看看\tkan4kan4\tkànkàn\tto take a look",
"情况\t情況\tqing2kuang4\tqíngkuàng\tsituation",
"报告\t報告\tbao4gao4\tbàogào\treport",
"会议\t會議\thui4yi4\thuìyì\tmeeting",
"加班\t加班\tjia1ban1\tjiābān\tto work overtime",
"技术方案\t技術方案\tji4shufang1an4\tjìshùfāngàn\ttechnical solution",
"电脑\t電腦\tdian4nao3\tdiànnǎo\tcomputer",
"黑屏幕\t黑屏幕\thei1ping2mu4\thēipíngmù\tblack screen",
"故障\t故障\tgu4zhang4\tgùzhàng\tmalfunction; fault",
"检查\t檢查\tjian3cha2\tjiǎnchá\tto check; to inspect",
];